---
title: "BIMM143class09Halloween"
format: pdf
---

```{r}
candy_file<-"candy-data.csv"
candy= read.csv(candy_file, row.names=1)
head(candy)
##candy-data.csv have to be in the same location
##as the Rstudio desktop in order it to render

##Q1.How many different candy types are in this dataset?
nrow(candy)
85
##the parentheses inside would be candy not candy_file

##Q2. How many fruity candy types are in the dataset?

sum(candy$fruity)
##remember $ you can use in column
##you can do $name of the column
##gives you the value true false 1,0
##then add up


as.logical(candy$chocolate)
##as.logical to make it into T/F instead of 1,0

candy[as.logical(candy$chocolate),]
##list all the rows that it is true or 1
```

```{r}
candy["Twix", ]$winpercent

##Q3/4. What is your favorite candy in the dataset 
##and what is it’s winpercent value?

candy["Kit Kat", ]$winpercent

##Q5. What is the winpercent value for 
##“Tootsie Roll Snack Bars”?

candy["Tootsie Roll Snack Bars",]$winpercent

```
```{r}
library("skimr")
skim(candy)

##Q6. Is there any variable/column that looks to 
##be on a different scale to the majority of the 
##other columns in the dataset?
##yes that winpercent goes upto 84%+
##all the other ones only go up to around 1%

##Q7. What do you think a zero and one represent for the candy$chocolate column?
##it talks about statistics. 
##so p25, p0, p50 means zero so
##and p75 and p100 was 1
##so this means 75% and greater
## of the data or candy was
##chocolaty.

##Q8. Plot a histogram of winpercent values

hist(candy$winpercent, breaks=20)

library(ggplot2)
ggplot(candy)+
aes(winpercent)+
  geom_histogram(binwidth=10)

##Q9. Is the distribution of winpercent values symmetrical?
##Not really. center is not on 50% and the 
##rise/run or "slope"
##is steeper below 50% than above

##Q10. Is the center of the distribution 
##above or below 50%?
##It seems to be below

```

```{r}
##Q11. On average is chocolate candy higher or 
##lower ranked than fruit candy?

##need to fist find out the chocolate column TRUE
##then turn into logical TRUE/FALSE 1/0
##then turn that result into the $winpercent to 
##get all the values and then find the mean
choc.inds<-as.logical(candy$chocolate)
choc.win<-candy[choc.inds,]$winpercent
choc.win

mean(choc.win)

fruit.inds<-as.logical(candy$fruity)
fruit.win<-candy[fruit.inds,]$winpercent
fruit.win
mean(fruit.win)

##choclate seems to be higher
##Q12. Is this difference statistically significant?

t.test(choc.win, fruit.win)
##yes significant difference statistically

```

```{r}
##Q13. What are the five least liked candy types in this set?
##this is how you do it
head(candy[order(candy$winpercent, decreasing=FALSE),], n=5)

##Q14. What are the top 5 all time favorite candy 
##types out of this set?

##default which is above is decreasing false.
##to make it from the top 5 make decreasing true
head(candy[order(candy$winpercent, decreasing=TRUE),], n=5)

```

```{r}
library(ggplot2)
##Q15. Make a first barplot of candy ranking 
##based on winpercent values.

ggplot(candy) + 
  aes(winpercent, rownames(candy)) +
  geom_col(fill="gray")
##Q16. This is quite ugly, use the reorder() 
##function to get the bars sorted by winpercent?

ggplot(candy) + 
  aes(winpercent, reorder(rownames(candy),winpercent)) +
  geom_col(fill="gray")

```
```{r}

##if chocolate true chocolate color
##If bar true brown color
##if fruity true pink color
my_cols<-rep("black", nrow(candy))
my_cols[as.logical(candy$chocolate)] = "chocolate"
my_cols[as.logical(candy$bar)] = "brown"
my_cols[as.logical(candy$fruity)] = "pink"

ggplot(candy) + 
  aes(winpercent, reorder(rownames(candy),winpercent)) +
  geom_col(fill=my_cols) 

##Q17. What is the worst ranked chocolate candy?
##Reeses Peanut Buttercup

##Q18. What is the best ranked fruity candy?
##starburst
```
```{r}
library(ggrepel)

# How about a plot of price vs win
ggplot(candy) +
  aes(winpercent, pricepercent, label=rownames(candy)) +
  geom_point(col=my_cols) + 
  geom_text_repel(col=my_cols, size=3.3, max.overlaps = 5)

##Q19. Which candy type is the 
##highest ranked in terms of winpercent 
##for the least money 
##- i.e. offers the most bang for your buck?
##Probably Reeses Miniatures

##also
ord <- order(candy$pricepercent, decreasing = FALSE)
head( candy[ord,c(11,12)], n=5 )

##Q20. What are the top 5 most expensive candy 
##types in the dataset and of these which is the
##least popular?


ord <- order(candy$pricepercent, decreasing = TRUE)
head( candy[ord,c(11,12)], n=5 )
```
```{r}
##Optional 21 step by step
ggplot(candy) + 
  aes(pricepercent, rownames(candy)) +
  geom_col(fill="gray")

ggplot(candy) + 
  aes(pricepercent, reorder(rownames(candy),pricepercent)) +
  geom_col(fill="gray")

# Make a lollipop chart of pricepercent
ggplot(candy) +
  aes(pricepercent, reorder(rownames(candy), pricepercent)) +
  geom_segment(aes(yend = reorder(rownames(candy), pricepercent), 
                   xend = 0), col="gray40") +
    geom_point()
```

```{r}
library(corrplot)
cij <- cor(candy)
corrplot(cij)

##Q22. Examining this plot what two variables are anti-correlated 
##(i.e. have minus values)?

##Q23. Similarly, what two variables are 
##most positively correlated?
##chocolate coming in bar form
##choclate's price percentage relative high
##chocolate winning percent high, people love'em

```
```{r}
pca <- prcomp(candy, scale=TRUE)
summary(pca)

plot(pca$x[,1:2])

plot(pca$x[,1:2], col=my_cols, pch=16)


```
```{r}
# Make a new data-frame with our PCA results 
##and candy data
my_data <- cbind(candy, pca$x[,1:3])

p <- ggplot(my_data) + 
        aes(x=PC1, y=PC2, 
            size=winpercent/100,  
            text=rownames(my_data),
            label=rownames(my_data)) +
        geom_point(col=my_cols)

p
```

```{r}
library(ggrepel)

p + geom_text_repel(size=3.3, col=my_cols, max.overlaps = 7)  + 
  theme(legend.position = "none") +
  labs(title="Halloween Candy PCA Space",
       subtitle="Colored by type: 
       chocolate bar (dark brown), 
       chocolate other (light brown), fruity (red), 
       other (black)",
       caption="Data from 538")

##library(plotly)
##ggplotly(p)


```

```{r}
par(mar=c(8,4,2,2))
barplot(pca$rotation[,1], las=2, ylab="PC1 Contribution")

##Q24. What original variables are picked up 
##strongly by PC1 in the positive direction? 
##Do these make sense to you?

##fruity and pluribus 
##make sense because it seems like those 
##tend to come
##in bags of multiple like skittles

```

